# Generated by Django 5.2.4 on 2025-08-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ask_askmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('answer1', models.CharField(max_length=255, verbose_name='Ответ 1')),
                ('answer2', models.CharField(max_length=255, verbose_name='Ответ 2')),
                ('answer3', models.CharField(max_length=255, verbose_name='Ответ 3')),
                ('answer4', models.CharField(max_length=255, verbose_name='Ответ 4')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Лёгкий'), (2, 'Средний'), (3, 'Сложный')], verbose_name='Уровень сложности')),
                ('correct_answer', models.PositiveSmallIntegerField(choices=[(1, 'Ответ 1'), (2, 'Ответ 2'), (3, 'Ответ 3'), (4, 'Ответ 4')], verbose_name='Правильный ответ')),
            ],
        ),
    ]
