# Generated by Django 5.2.4 on 2025-08-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionModel',
        ),
    ]
