# Generated by Django 5.2.4 on 2025-08-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_question_questionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('lucky', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
