# Generated by Django 5.2.4 on 2025-08-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fact',
            new_name='FactModel',
        ),
    ]
