# Generated by Django 5.2.4 on 2026-02-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplimentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('for_how', models.CharField(choices=[('him', 'him'), ('her', 'her')], max_length=255)),
            ],
        ),
    ]
